# 1. Usa uma imagem base oficial do Python para o ambiente de produção
FROM python:3.12-slim

# 2. Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# 3. Copia o arquivo de requisitos e instala as dependências
# Isso é feito primeiro para otimizar o cache da Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copia o resto do código da sua aplicação
COPY . .

# 5. Define a porta que o contêiner irá escutar.
# O Cloud Run injeta a porta real via variável de ambiente PORT
ENV PORT 8080

# 6. Comando de inicialização: Usa o Gunicorn para servir o aplicativo Flask.
# O padrão 'main:app' funciona se o seu objeto Flask for chamado 'app' no arquivo 'main.py'
CMD exec gunicorn --bind :$PORT --workers 1 main:app

